### ISSUE TITLE
Adding Linux Mint support

### ISSUE THREAD

**Issue by philipzae** [Douane/Douane#23]
Douane works well on ubuntu, but i need linux mint support. :)

Here are my findings pulled from #16.

> it installed successfully and when i turned on the firewall a number of popups showed up, but was only able to access the last popup which was for qbittorrent. i clicked yes to allow qbittorrent, but the rule wasnt added to the 'rules' tab, and no other firewall popups appeared after that. then i looked at the 'general' tab again and i see an error, as included in the image (unfortunately the screenshot didnt save the tooltip which came up but it had some text about freedesktop.org). I closed the app and then opened it up again and the auto start wasnt enabled and the error now says 'D-Bus service org.zedroot.Douance not found'.

**Comment by samumi** [comment]
Hello, Linux Mint 17.2 XFCE user here. Compiled the app as described and also got  the "D-Bus service org.zedroot.Douane" and "Missing Popup" error described by philipzae.

I was only able to unistall dkms. How to uninstall the rest?

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/23).
