### ISSUE TITLE
http connection logs

### ISSUE THREAD

**Issue by philipzae** [Douane/Douane#25]
i'm assuming douane is saving logs of atleast requests that are denied according to the firewall rules, so i'd like to suggest the saving of http request to a long, as i havent found a good http sniffer application on linux. something as simple as request type (get, post, head, etc), application making the request, and url.

**Comment by raymondsteers** [comment]
You might try the browser plugin called uBlock Origin as it has a very complete and easy to access log of all browser requests. 
![image](https://cloud.githubusercontent.com/assets/8668107/9628513/1554f4e0-5174-11e5-8c22-0c7c043d12ff.png)

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/25).
