### ISSUE TITLE
Discussion about Douane

### ISSUE THREAD

**Issue by philipzae** [Douane/Douane#27]
I visited a page entitled "Major Linux Problems on the Desktop 2014 edition" and one of the points the author stated was "No application level firewall (to clarify this point - there's no way to block or allow certain applications to access the Internet, e.g. /usr/bin/firefox) - SeLinux doesn't solve this problem because SeLinux policies by default don't apply to normal user applications and SeLinux is not a firewall solution per se.". So i commented to say that Douane was available.

http://linuxfonts.narod.ru/why.linux.is.not.ready.for.the.desktop.current.html#comment-1352737882

**Comment by demchenkoe** [comment]
Hi.
Please add advanced info about destination IP  (aka whois) to the allow/deny dialog.
This is IMHO more usability.

**Comment by zedtux** [comment]
@demchenkoe your request has nothing to do with this issue. Please open a feature request in [the dialog repo](https://github.com/Douane/douane-dialog/issues)

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/27).
