### ISSUE TITLE
douane service fails on opensuse 13.1

### ISSUE THREAD

**Issue by bonanza123** [Douane/Douane#32]
I tried to it running on OpenSuse 13.1, but I'm receiving some errors when trying to start the service. The dkms part worked fine and I'm able to load the corresponding module. But when trying to start the service this happens:

b:/home/bon # lsmod | grep douane
douane                 17508  0
b:/home/bon # modprobe  douane
b:/home/bon # service douane start
Job for douane.service failed. See 'systemctl status douane.service' and 'journalctl -xn' for details.
b:/home/bon # systemctl status douane.service -l
douane.service - SYSV: douane is the daemon process of the Douane firewall application. This firewall is limiting access to the internet on application bases.
   Loaded: loaded (/etc/init.d/douane)
   Active: failed (Result: exit-code) since Sat 2014-06-21 12:08:30 CEST; 3s ago
  Process: 3867 ExecStart=/etc/init.d/douane start (code=exited, status=127)

Jun 21 12:08:30 b.site systemd[1]: Starting SYSV: douane is the daemon process of the Douane firewall application. This firewall is limiting access to the internet on application bases....
Jun 21 12:08:30 b.site douane[3867]: /etc/init.d/douane: line 23: log_daemon_msg: command not found
Jun 21 12:08:30 b.site douane[3867]: /etc/init.d/douane: line 32: start-stop-daemon: command not found
Jun 21 12:08:30 b.site douane[3867]: /etc/init.d/douane: line 33: log_end_msg: command not found
Jun 21 12:08:30 b.site systemd[1]: douane.service: control process exited, code=exited status=127
Jun 21 12:08:30 b.site systemd[1]: Failed to start SYSV: douane is the daemon process of the Douane firewall application. This firewall is limiting access to the internet on application bases..
Jun 21 12:08:30 b.site systemd[1]: Unit douane.service entered failed state.
b:/home/bon # journalctl -xn
-- Logs begin at Sat 2014-06-21 12:01:06 CEST, end at Sat 2014-06-21 12:08:37 CEST. --
Jun 21 12:08:30 b.site douane[3867]: /etc/init.d/douane: line 23: log_daemon_msg: command not found
Jun 21 12:08:30 b.site douane[3867]: /etc/init.d/douane: line 32: start-stop-daemon: command not found
Jun 21 12:08:30 b.site douane[3867]: /etc/init.d/douane: line 33: log_end_msg: command not found
Jun 21 12:08:30 b.site systemd[1]: douane.service: control process exited, code=exited status=127
Jun 21 12:08:30 b.site systemd[1]: Failed to start SYSV: douane is the daemon process of the Douane firewall application. This firewall is limiting access to the internet on application bases..
-- Subject: Unit douane.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
## -- Unit douane.service has failed.

-- The result is failed.
Jun 21 12:08:30 b.site systemd[1]: Unit douane.service entered failed state.
Jun 21 12:08:37 b.site radvd[708]: attempting to reread config file
Jun 21 12:08:37 b.site radvd[708]: no linklocal address configured for eth0
Jun 21 12:08:37 b.site radvd[708]: resuming normal operation
Jun 21 12:08:37 b.site radvd[708]: [Jun 21 12:08:37] radvd: no linklocal address configured for eth0

**Comment by intika** [comment]
Fixed in the current release, can you try again

**Comment by intika** [comment]
should be closed

**Comment by zedtux** [comment]
@bonanza123 can you please update this issue?

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/32).
