### ISSUE TITLE
Is there a 'successfully build/compatible on page'?

### ISSUE THREAD

**Issue by MartijnDevNull** [Douane/Douane#35]
Since for now there aren't any prebuilt packages, is there a page listing on which platforms Douane can run? Compiling and installing all the dependencies for this project can take a while, for me it would be reassuring knowing someone else already has been able to build it before on their platform. (Even though the install can differ from computer to computer)

I'm on Debian Jessie, which I would think would work since Ubuntu comes from Debian but in #23 Linux Mint doesn't while that is built on Ubuntu..?

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/35).
