### ISSUE TITLE
current Arch pkgbuilds in AUR appear to be broken

### ISSUE THREAD

**Issue by brett** [Douane/Douane#39]
- init script depends on missing LSB functions
- lack of dependency on kernel header pkg

Will the packaging scripts be going in their own repo so that folks can submit pull requests?

**Comment by skddc** [comment]
Would be great to have working Arch packages!

**Comment by chaosdrop** [comment]
AUR packages are still broken (a year later) Checksums don't match, and the package name paths are wrong. eg: They look for packagename-git when everything in the src folders don't have -git. 

So you can get things installed by skipping the checksum (bad) and renaming the files or renaming the package (bad) also the  "pkgver" script is failing so it had to be changed as well. (also bad)

**Comment by zedtux** [comment]
Sorry to hear about this, but I'm not in charge of packaging Douane. As I previously said @pulser make it.
See if he can help or just fix the package? (Sorry I have no idea about the process of creating packages on Arch).

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/39).
