### ISSUE TITLE
D-Bus service org.zedroot.Douane not found [using Systemd]

### ISSUE THREAD

**Issue by y9yjRQcg7F** [Douane/Douane#40]
I'm using a freshly updated Arch Linux.  I've started the daemon using systemd's systemctl.  For some reason, the AUR package still installed an init.d file, despite the fact that I use Systemd.  When I run douane-configurator, there is an error icon next to the 'ON' switch.  If I press the 'ON' switch, it does ask for my root password.  If I hover over the error icon, it says, "D-Bus service org.zedroot.Douane not found."

Wat do?

**Comment by zedtux** [comment]
It seems something went wrong after having entered the root password. Have a look to the `/var/log/douane.log` file you should find an error which could help you.

**Comment by y9yjRQcg7F** [comment]
No /var/log/douane.log file exists.

I just checked the status of douane and got the following back:

    systemctl status douane-daemon.service
    ● douane-daemon.service - Douane Daemon
       Loaded: loaded (/usr/lib/systemd/system/douane-daemon.service; enabled; vendor preset: disabled)
       Active: active (exited) (Result: exit-code) since Tue 2015-01-06 12:41:10 EST; 27min ago
 Main PID: 511 (code=exited, status=127)
       CGroup: /system.slice/douane-daemon.service

    Jan 06 12:41:10 asus douane[511]: /etc/init.d/douane: line 12: /lib/lsb/init-functions: No such file or directory
    Jan 06 12:41:10 asus douane[511]: /etc/init.d/douane: line 23: log_daemon_msg: command not found
    Jan 06 12:41:11 asus douane[511]: /etc/init.d/douane: line 32: start-stop-daemon: command not found
Jan 06 12:41:11 asus douane[511]: /etc/init.d/douane: line 33: log_end_msg: command not found
Jan 06 12:41:11 asus systemd[1]: douane-daemon.service: main process exited, code=exited, status=127/n/a

**Comment by zedtux** [comment]
You found the issue and it seems to be the same as Douane/douane-daemon#3.

**Comment by y9yjRQcg7F** [comment]
I installed start-stop-daemon and then was able to successfully start the douane-daemon.  It immediately started functioning as it should.  After about 30 minutes or so I got a kernel panic.  The only error I could find in /var/log/douane.log is this:

    06/01/2015 14:36:47 | daemon | ERROR | [rules_manager.cpp::RulesManager:135]: Unable to open the file /opt/douane/rules

**Comment by y9yjRQcg7F** [comment]
I should also mention that after only 30 minutes of running, douane created 2.2 MB log.

**Comment by zedtux** [comment]
Douane is not yet stable. The most important issue is the kernel panic, then the daemon taking too much memory and also the log file.

For now, I have asked several times to have a crash file in order to be able to analyse it and fix the kernel panic but nobody is able to do it.
I can only ask you to join the long issue Douane/douane-dkms#3 and cross my fingers that you will be the one :)

**Comment by zedtux** [comment]
Just to avoid that you have to read the entire issue, here is the link to have crash installed : http://blog.zedroot.org/linux-kernel-debuging-using-kdump-and-crash/

**Comment by y9yjRQcg7F** [comment]
Recompiling the kernel to get kdump running on my primary rig would be a bit too much research and work.  I'll get an Ubuntu VM setup and follow your instructions to save myself time.

**Comment by zedtux** [comment]
Nice thank you.
