### ISSUE TITLE
autostart not working in all environments (systemd and so on)

### ISSUE THREAD

**Issue by junkvolny** [Douane/Douane#41]
Script located at /etc/init.d/douane was not automatically started at startup, even when auto-startup was configured.

Running from command line inside /etc/init.d directory:
# sudo update-rc.d douane defaults

Fixed the problem. Maybe add this to installation script? I am a bit new to Linux, I don't know if this is distro specific.

I found the problem with adding logging to /etc/init.d/douane and watch no log to be produced upon system boot. Without this fix, daemon had to be manually restarted (with sudo), either from command line or using douane-configurator.

Tested on Kubuntu 14.04, 32-bit (x86), running inside VirtualBox.

**Comment by zedtux** [comment]
Can you please post the logs before and after ?

In my remembering, the feature auto start was working.

**Comment by zedtux** [comment]
Also as an info: Bare in mind that the project is suffering of a kernel panic (Others and myself do not have time to fix it) so please be careful using Douane.
You can refer to the issue douane-dkms#3. I have a blog post explaining how to install the crash command in order to provide me the dump (as of today, nobody were able to provide me with a crash dump file. And for me it was working on Ubuntu).

**Comment by junkvolny** [comment]
Indeed, I myself have issues with system freeze. I will be careful using it, that's why I test it in virtual machine first. In the meantime I will test some more, hoping to find out cause of freeze, or I will try to make a crash dump.

**Comment by rambo919** [comment]
Same problem, nothing even happens in the log file when the autostart option is toggled...
Had to skip "systemctl daemon-reload" during install because I do not use systemd... dunno if that's related.

Here is the log file anyway

http://pastebin.com/R2uPVD8q

**Comment by zedtux** [comment]
I'm now using Debian, which is using systemd so I could spend some time on the systemd integration but then leaving without any support for the init script.

**Comment by mr-blobbyyy** [comment]
I just got to `systemctl: command not found` in the compile process. What should I do now, just forget about it and continue with `sudo service douane start` ?

Linux Mint 17.3 Xfce, kernel 3.19.0-32

**Comment by mr-blobbyyy** [comment]
Alright, I perhaps foolishly did `sudo update-rc.d douane defaults` outside of the /etc/init.d directory, it game me a warning about missing LSB information. I started the deamon, coudn't access anything on the internet (including the remaining github code...why is this so hard), stopped the deamon, finished the rest of the compile process, restarted the deamon again, it started working...for a while, but now applications no longer show the dialogue box. Opening the "configurator" was a puzzle as well, the desktop configuration file had the target, "/usr/bin/douane-configurator" -- which doesn't exist, which lead me to believe something seriously messed up. I was able to open it with `./douane-configurator` in the douane-configurator folder, but it's obvious that despite all the reqs installed, this isn't working on Xfce. How do I kill the init scripts and is it okay to just trash the Douane folder? I'm sorry but I'm so mad at wasting nearly half a day trying to find application firewalls. I had hope for APF until I realized that was non-functional abandonware too commonly found in ubuntu's repos.

Maybe I'll try bash's instructions at https://github.com/Douane/Douane/issues/47

I never realized how much I took win7's firewall for granted.

**Comment by zedtux** [comment]
@mr-blobbyyy Douane is compatible with GNOME only as I'm a GNOME user. In the case someone wants to have it working on Xfce or any other desktop environment, he "just" have to fork [douane-dialog](https://github.com/Douane/douane-dialog) and implement the UI instructions for the environment.

The Compatibility section on http://douaneapp.com/ gives this information. In case someone implements Douane in other environments, I'll update this section.

**Comment by intika** [comment]
can you try with the last release,
also you will need initscripts package it's missing on your system
https://pkgs.org/download/initscripts
if still does not work you can add chkconfig package
and you could also try to reinstall systemd package

init.d folder is part of those packages

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/41).
