### ISSUE TITLE
wiki - kernel module compilation

### ISSUE THREAD

**Issue by junkvolny** [Douane/Douane#42]
In page https://github.com/Douane/Douane/wiki/Compilation

Shouldn't there be instead of:
$ sudo make dkms
lines:
$ make
$ sudo make install
?

For me, "sudo make dkms" just prints:
make: dkms: Command not found
make: *** [dkms] Error 127

**Comment by zedtux** [comment]
This is because you didn't read the dependencies page (https://github.com/Douane/Douane/wiki/Dependencies) where you will see that you have to install the `dkms` page.

**Comment by junkvolny** [comment]
Sorry, my bad, too much (re)installing.  *embarrassed*
To be sure, I made installation script for testing clean install on Ubuntu/Kubuntu, if it helps anybody:  
http://pastebin.com/CJSpizkR

**Comment by zedtux** [comment]
Nice :)
