### ISSUE TITLE
No icons generated after installation

### ISSUE THREAD

**Issue by unidesign** [Douane/Douane#43]
After compilation and installation the manual page implifies that icons/shortcuts are now generated,
but that's not true at least for linux mint. Here is explained how to shortcut an application for linux systems: http://www.sysads.co.uk/2014/04/install-latest-eclipse-ide-ubuntu-14-04-13-10/

It is also hard to generate a shortcut manually because honestly I dont know which program to start in which order...

**Comment by zedtux** [comment]
> It is also hard to generate a shortcut manually because honestly I dont know which program to start in which order...

The normal behavior is that you only start the `douane-configurator` and the rest is started from it.

**Comment by unidesign** [comment]
Okay that's good to know, thanks.
