### ISSUE TITLE
Show whole path of file additionally

### ISSUE THREAD

**Issue by unidesign** [Douane/Douane#44]
For some programs I'm not sure what's behind the name of this application/service so getting the whole name additionally (maybe on click of the blocked app name it could yield to folder) would be nice.

E: to be more precise I mean the window which appears if Douane askes for allow or deny the app.

**Comment by zedtux** [comment]
Please @unidesign read the page [Architecture](https://github.com/Douane/Douane/wiki/Architecture) in order to avoid opening issues at the wrong place :)

**Comment by zedtux** [comment]
I'm closing this one
