### ISSUE TITLE
Push your project to Debian/Ubuntu repos as soon as possible! 

### ISSUE THREAD

**Issue by free5lot** [Douane/Douane#45]
Please, push your project to Debian/Ubuntu repos as soon as possible! 
Your firewall with per-application approach seems to be a great thing with no appropriate alternative there.
So, please, allow more people who are concerned with security or internet activity on their computers to use it, even if they're not confident enough to build it out of sources themselves.
I think Ubuntu's PPA will work (at least), but this firewall type deserves to be in mainstream repos.

**Comment by zedtux** [comment]
Thank you for your issue :)

I had worked on the packaging for Ubuntu in the past but it's time consuming so I've decided to focus on the development only and let people expert in packaging (or having time) to do it instead.

Sorry to not help more on this. In the other hand I'm fully available to help anyone about dependencies and so on.

**Comment by skddc** [comment]
Sorry to just jump in here like that, but maybe you could consider publishing the Arch packages from https://github.com/Douane/Douane/wiki/Archlinux-Packaging on AUR sometime? :)

**Comment by free5lot** [comment]
Thanks for your affords! Anyway, now you'll have one more unclosed enhancement-issue :)

Let me be clear, no matter how good your project would be, it won't make the world a better place if no one would use. And now you have some users, but quite high-level skills required to be one.
On the other hand you're making a GUI application, that would be an easy to use for a average GNU/Linux user. But how does it work if it's not easy to install for him? 

I wish you luck with your project and hope there'll be a Ubuntu/Debian's repos maintainer for it or you'll made it yourself at some point.

**Comment by zedtux** [comment]
@free5lot I fully agree with you and you're right ! In the case you know a way to promote the project to packagers, it would be great.

@skddc Welcome ! :) As I wrote I don't have the time (nor the knowledge) sorry. You should contact @pulser the guy who did the Arch package.

**Comment by free5lot** [comment]
@zedtux maybe you should search for a maintainer on some Ubuntu-related forums or send an offer to some maintainers of other security/firewall related packages in the Ubuntu/Debian repository or PPA. Maybe you'll find one with a suitable knowledge and spare time for you project there.

**Comment by qazip** [comment]
Is there any news regarding this? Couldn't find a PPA with Douane

**Comment by zedtux** [comment]
Thank you @free5lot for your comment, I'm using Debian (but I was using Ubuntu at the time of the development of Douane).

@qazip Unfortunately I don't have the time to do this task.

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/45).
