### ISSUE TITLE
Installing on *buntu

### ISSUE THREAD

**Issue by eclipsed-ninja** [Douane/Douane#46]
Awesome software I must say, Can't wait to contribute towards this project.

A little issue I found is dbus include; in file dbus/dbus_server.h (line 5), dbus files are in 
dbus-1.0/dbus/dbus.h (in case of *buntu, most probably debian aswell)

Made this change hardcoded in the file, trying to resolve the missing dbus-arch-deps.h
Will keep you updated on my build, once it's done I'll see if I can build this into a package (too many dependencies though :/ )

**Comment by zedtux** [comment]
Alright, thank you @eclipsed-ninja for your issue. I'm surprised as I have developed the software on Ubuntu and I've used it on Debian.

Have you followed [the compilation guide](https://github.com/Douane/Douane/wiki/Compilation) ?

**Comment by eclipsed-ninja** [comment]
Yeah, I'm following the same doc,

Weird that you didn't face them, do you have a list of dependencies handy ?
I used libdbus-1-dev for the dbus headers, went straight to /usr/include/dbus-1.0/dbus/
also, I'm getting a missing dbus-arch-deps (working on resolving it)

**Comment by eclipsed-ninja** [comment]
Sorry, just found what I was looking for
