### ISSUE TITLE
locks up whole system on kernel 4.1.2

### ISSUE THREAD

**Issue by bash64** [Douane/Douane#47]
Linux Mint 17.2 64bit cinnamon
Kernel 4.1.2

I compiled for this kernel.
Every time I launch douane-configurator  and turn on douane it locks up my whole laptop.
I must force it off.

What kernels has this been tested with?

**Comment by zedtux** [comment]
I believe it has been tested only on 3.x kernel versions.

If you could try to follow the instruction on my blog : http://blog.zedroot.org/linux-kernel-debuging-using-kdump-and-crash/ you would then be able to give me the crash file so that I could analyze what is going wrong.

**Comment by bash64** [comment]
I need to recompile for 3.18, currently it is compiled for 3.13.
How do I start over clean?

When I do sudo make dkms I get a lot of errors about existing folders.
When I do sudo make clean dkms I am told I cannot do this more than once.



dad@dad-pc ~/Douane/douane-dkms $ sudo make clean dkms
make -C /lib/modules/3.18.6-031806-generic/build M= clean
make[1]: Entering directory `/usr/src/linux-headers-3.18.6-031806-generic'
make[1]: Leaving directory `/usr/src/linux-headers-3.18.6-031806-generic'
Installing Douane Linux kernel module version 0.8.2...
Error! DKMS tree already contains: douane-0.8.2
You cannot add the same module/version combo more than once.
make: *** [dkms] Error 3

**Comment by zedtux** [comment]
`make clean dkms` do not exists in the Makefile.

You have to use `make cleandkms` in order to remove the module and then use `make dkms` to re-install it.

**Comment by bash64** [comment]
Hello,

I have gotten around to fully testing Douane in Linux Mint 17.2 64 bit 
with Cinnamon Desktop.
It is working well.
If I can help do anything to make this software work with kernel 4 just 
let me know.



Here is the documentation I have made for installation in my OS:

Status: Verified and fully tested. However, it does not work with kernel 
4 at this time.

Douane - an easy to use firewall that blocks apps from reaching the internet

Douane home page:
http://douaneapp.com/


Douane Install page:
https://github.com/Douane/Douane/wiki/Compilation
https://github.com/Douane/Douane/wiki/Dependencies

Simplified install:

#dependencies first...
 >sudo apt-get install build-essential libboost-filesystem-dev 
libboost-regex-dev libboost-signals-dev policykit-1 libdbus-c++-dev 
libdbus-1-dev liblog4cxx10-dev libssl-dev libboost-signals-dev 
libdbus-c++-dev libdbus-1-dev liblog4cxx10-dev libgtkmm-3.0-dev python3 
python3-gi policykit-1 python3-dbus

# if you have already installed this once but have a new kernel and need 
to recompile then do this first to clean out the old copy...
cd ~/Douane/douane-dkms
sudo make cleandkms

#now install fresh with all the different pieces from github.com...
cd ~
mkdir Douane
cd Douane/
git clone https://github.com/Douane/douane-dkms
cd douane-dkms
sudo make dkms
cd ~/Douane
git clone https://github.com/Douane/douane-daemon
cd douane-daemon
git submodule init && git submodule update
make
sudo make install

cd ~/Douane
git clone https://github.com/Douane/douane-dialog
cd douane-dialog
git submodule init && git submodule update
make
sudo make install
cd ~/Douane
git clone https://github.com/Douane/douane-configurator
cd douane-configurator
sudo python3 setup.py install

#now configure Douane
 >douane-configurator

Set 'Use Douane to filter my network traffic' to ON.
Set 'Auto start Douane on boot' to ON.
Reboot.

I find that the daemon does not start on boot, but the dialog box for 
Douane does.
Personally I have created a desktop icon for the configurator and I turn 
Douane ON manually after booting.

If you have ever used one of these tools for Windows (like Avast 
antivirus) you know that it will detect a new program and block it 
initially.
By the time you decide whether to allow or deny the app the app may have 
given up or crashed.
The easy solution is to kill the app and start it a 2nd time.
I find that it always works the 2nd time and there after.

Sometimes, I experienced desktop lockups using this tool, however, this 
may have been related to the new Cinnamon Desktop 2.6.
There is a new hotkey if your desktop locks up completely, it is 
CTL-ALT-ESC.

**Comment by bash64** [comment]
Just a note.
Douane was locking up, but I found on your forums that virtualbox may 
have been the issue.
I checked and virtualbox was having an issue.
It was installed for 3.13 and I was booted into 3.18.
After removing virtualbox completely all of the locking up has stopped.

**Comment by zedtux** [comment]
Nice @bash64 !

I can work on the 4.x kernel version issue if I have a crash file (see my first comment).

**Comment by bash64** [comment]
Working as a redhat administrator I am familiar with kdump.
Honestly, it may have been virtualbox that caused lockups under kernel 4.
I will recompile for kernel 4 tonight and let you know.
Your product is so good I won't even use virtualbox any more just so I 
can have Douane.
:-D

**Comment by bash64** [comment]
I recompiled for kernel 4 and it locks up the whole system immediately.
Will get you a kdump.
Later on.

**Comment by zedtux** [comment]
Thank you @bash64 for your comments ! I'm really happy that you like my app ! :) And sorry for the freeze ...

**Comment by Guimli** [comment]
Tested on Linux Mint 17.2 with https://github.com/Douane/douane-dkms/pull/16.
Working for me.

**Comment by zedtux** [comment]
@bash64 can you give a try to the @Guimli's branch and update us?

**Comment by bash64** [comment]
sure. I did a beta upgrade to linux mint 18 (ubuntu 16.04) so I would be 
testing with that instead of mint 17.
but it is still kernel 4.4 for me.

**Comment by zedtux** [comment]
@bash64 in case you need help, feel free to ask :)

**Comment by bash64** [comment]
Linux mint 18 beta went belly up. I am back on 17.3 64bit.
I have a job interview today. I will get to it sometime this evening.

**Comment by bash64** [comment]
See Guimil net filter thread for my error message.

**Comment by zedtux** [comment]
@bash64 as I said in #52 the Douane stability has been improved a lot, can you please check and update this issue?

**Comment by zedtux** [comment]
@bash64 another improvement has been merged on the `master` branch. Please have a look and let me know 😃

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/47).
