### ISSUE TITLE
Daemon stops when I try to add rule for ossec-agentd

### ISSUE THREAD

**Issue by cynicbox** [Douane/Douane#48]
I have OSSEC installed on my machine. OSSEC system runs agent which send some data through the network. OSSEC runs under separated user. When I try to add rule for ossec-agentd douane-dialog closes and douane daemon stops.

Ubuntu 14.04.2 64-bit, kernel 3.13.0-61-generic
Douane 0.9.0
OSSEC HID 2.8

How do I to add rule manually?

**Comment by zedtux** [comment]
@cynicbox can you please start the daemon manually (without going through the configuration) with the `-D` flag (for debug mode) and post the log file (`/var/log/douane.log`) ?

**Comment by cynicbox** [comment]
Alas, I can't intercept time of agent activity. douane-dialog does not appear in time of expectation. Manual running of dialog shows no any network activity. Daemon blocks any app without rule in list.

**Comment by zedtux** [comment]
Normally the `-D` flag is supposed to make the daemon logging everything happening which means you should then see some logs about the agent traffic at the end of the day in this log file.

Another thing could be to enable the debug in the kernel module but this is a bit more tricky and can create big log files.

**Comment by cynicbox** [comment]
Alright, I got log but found nothing useful inside. Last rows before stopping look like

11/08/2015 12:06:52 | daemon | DEBUG | [netlink_listener.cpp::NetlinkListener:97]: NetlinkListener::send_rule ALLOW for /bin/ossec-agentd
11/08/2015 12:06:52 | daemon |  INFO | [rules_manager.cpp::RulesManager:89]: Currently 6 pending rules

**Comment by zedtux** [comment]
Well I disagree with you :)

It looks like you've already allowed the OSSEC agent but you still have 6 pending validations (for 6 different applications).

Now you should start the dialog process also with the `-D` flag to have also the debug enabled and see why you do not have the window appearing

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/48).
