### ISSUE TITLE
archlinux PKGBUILD error

### ISSUE THREAD

**Issue by sharan01** [Douane/Douane#49]
i am using makepkg to build douane-dialog,  PKGBUILD from here https://github.com/Douane/Douane/wiki/Archlinux-Packaging

but i get error check line number 32 
```
error: macro "bind_property" requires 4 arguments, but only 3 given
     BindingFlags flags = BINDING_DEFAULT)
```
https://gist.github.com/sharan01/6e8201de9ec378a3c1f5

how to fix the error?

thanks

**Comment by zedtux** [comment]
Thank you for trying Douane. Your issue seems related to PKGBUILD, not to Douane, so I close this issue. Sorry I don't know at all Arch.
