### ISSUE TITLE
Blank  box

### ISSUE THREAD

**Issue by pyprism** [Douane/Douane#50]
I am using Ubuntu 15.04. Its doesn't show allow/deny option in the box.

![screenshot from 2015-09-23 19 49 48](https://cloud.githubusercontent.com/assets/1469242/10046721/497acb78-622c-11e5-84ee-0c33e902e79f.png)

**Comment by zedtux** [comment]
:-o  ... Can someone else confirm this issue / have a look in case you're a dev ?

**Comment by TechnoKickAss** [comment]
I can confirm it on Elementary OS.

**Comment by zedtux** [comment]
> It appeared sometimes.

Is it the same @pyprism for you ? Does it appears sometimes or you never ever have the content of the window ?

**Comment by pyprism** [comment]
Yes its same for me .

**Comment by zedtux** [comment]
Alright. Can you please run Douane dialog in debug mode (passing the `-D` flag) in a terminal and copy/paste the output ?

**Comment by zedtux** [comment]
@pyprism were you able to reproduce the issue ?
