### ISSUE TITLE
douane-dialog build issue on Fedora 22/23

### ISSUE THREAD

**Issue by shpedoikal** [Douane/Douane#51]
Build log:

http://pastebin.com/crKBzB3E

**Comment by zedtux** [comment]
It looks like a dependency conflict to me but not sure.

**Comment by shpedoikal** [comment]
Forgot to mention that I had a huge number of errors until I manually added -std=c++11 to the build. After that I got this smaller number of errors.

Can you post your compiler version?  Thanks

**Comment by shpedoikal** [comment]
I also see these errors on Fedora 23, so I've updated the title to reflect that.

**Comment by czapa-ols** [comment]
The problem is within dbus-c++: the collision is between the macro bind_property in dbus-c++/interface.h and the method bind_property in glibmm/binding.h

`#include <gtkmm.h>` before `#include<dbus-c++/dbus.h>` in dbus/douane.h and dbus/dbus_client.h seams to fix issue (at least dialog builds)

**Comment by zedtux** [comment]
@shpedoikal do you have any news since @czapa-ols did a PR which has been merged in master?

**Comment by intika** [comment]
had the same issue on a fedora like system... and fixed it @zedtux merged the fix can you git clone and try again

**Comment by intika** [comment]
should be closed (also its a duplicate of some start daemon issues)

**Comment by zedtux** [comment]
@intika please link issues together if there are duplicates.

@shpedoikal and @czapa-ols can you please update this issue?

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/51).
