### ISSUE TITLE
Ubuntu Wily (15.10) Kernel 4.2.0 + douane-daemon => System Freeze

### ISSUE THREAD

**Issue by bzkdjc** [Douane/Douane#52]
Hi, 
`douane-daemon` immediately **freezes whole system** as soon as launched after build, on Ubuntu Wily 15.10 with its default kernel 4.2.0.

**Comment by zedtux** [comment]
Thanks @bzkdjc for having reported this.

**Comment by Afforess** [comment]
I also experienced this. Ubuntu Wily + Kernel 4.3.0-040300-generic.

**Comment by zedtux** [comment]
I have prepared a Debian box yesterday (Kernel 4.3.0). I'm going to do some testing myself, but in case you'd like to help me, please send me the crash file after a system freeze (see [my blog article](http://blog.zedroot.org/linux-kernel-debuging-using-kdump-and-crash/) in order to configure your machine and get this crash file).

**Comment by TomAshley303** [comment]
Is this fixed? I just installed all the deps just to find this thread.

**Comment by dansavio** [comment]
I'm also very interested in using this with a 4.x kernel

**Comment by zedtux** [comment]
I wasn't able to work on this until now. As I said before, you can have a look at [my blog article](http://blog.zedroot.org/linux-kernel-debuging-using-kdump-and-crash/) in order to configure your machine and get a crash file which would help me in order to see the bug and try to fix.

**Comment by uberschlock** [comment]
Hi. My system freezes as well. I attached some info from `crash`. Hope it's helpful.
[crash output.txt](https://github.com/Douane/Douane/files/187790/crash.output.txt)

**Comment by zedtux** [comment]
Thank you @uberschlock I'll have a look

**Comment by Sharsie** [comment]
Do you need any assistance in debugging it any further? I got the same error while building as https://github.com/Douane/Douane/issues/51#issue-115116179 on kubuntu 15.10 and also got a freezes on 14.04, cant remember kernel version, but it's current version

**Comment by zedtux** [comment]
I need time actually. I'm sorry to not be more reactive on this project.

**Comment by Guimli** [comment]
Hello

NetFilter Hook function has changed
[douane-dkms.patch.txt](https://github.com/Douane/Douane/files/253246/douane-dkms.patch.txt)

**Comment by zedtux** [comment]
Hey thank @Guimli :) Can you please open a PR here: https://github.com/Douane/douane-dkms ?

**Comment by Guimli** [comment]
I'm studying the differences between netfilter versions. There are a major modification from kernel 4.0 to 4.1. The in and out net_device moved to the new nf_hook_state_init function. I'm not developer, i cannot implement this new function.

**Comment by zedtux** [comment]
Thank you @Guimli for those information. I will check as we already have [a kernel 4.4 compatibility PR](https://github.com/Douane/douane-dkms/pull/15) open, maybe it is fixing this point.

**Comment by zedtux** [comment]
It looks like it's fixing this point :)

**Comment by Guimli** [comment]
Pull Request send !

**Comment by zedtux** [comment]
@bzkdjc Douane stability has been improved a lot thanks to @Guimli. Can you please have a look and update this issue?

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/52).
