### ISSUE TITLE
Support handling localhost requests and external network requests separately

### ISSUE THREAD

**Issue by ssokolow** [Douane/Douane#53]
I like Douane in principle, but it would be a lot more useful to me if I could configure it to automatically allow requests on the loopback adapter and only bother me about requests that actually leave my PC. (Both for minimizing annoyance and as a second layer of defense on daemons which need a local loopback socket but should never be exposed to the wider world.)

As-is, its behaviour is so counter-intuitive that, at first, I had to double-check that I hadn't misconfigured my system when it asked permission to let things like LCDd, vim.gtk, and hddtemp use the network. (They all have things like `Bind=127.0.0.1` in their config files and communicate via loopback sockets.)

I'm not asking for fancy filtering either. (I already saw a feature request for that.) I'm just asking for a toggle along the lines of "Silently allow communication via the loopback adapter"

As-is, I can't even trust it to reliably verify that my DRM-free games aren't phoning home because I had to allow communication for various various language runtimes which only perform loopback requests in normal operation here.

**Comment by zedtux** [comment]
Thank you @ssokolow for your comment.

Just for me to be sure to well understand your need, you would like to have a kind of checkbox in the configurator, which would allow automatically all the network traffic on the loopback (127.x.x.x) ?

**Comment by ssokolow** [comment]
Yes.

Specifically, if I enable it, I'd like to see...
1. No dialog for `lo` traffic
1. A dialog for `eth0` traffic, even if the application already made successful `lo` requests before.
1. If I deny an application Internet/LAN access, then `lo` must still work.

(I've got iptables configured to automatically pass through `lo` traffic because many applications use it as an alternative to UNIX domain sockets, shared memory, pipes, D-Bus, etc. with a more cross-platform API)

That would have two benefits:
1. Fewer interruptions during normal operation.
1. Douane can catch compromises where an application that's only supposed to do loopback suddenly wants to do LAN/Internet communication.

**Comment by zedtux** [comment]
Great, it's super clear.

**Comment by zedtux** [comment]
@ssokolow in the case you would like to help me, fixing the kernel freeze, I wrote a blog article which explains how to debug a kernel module : http://blog.zedroot.org/linux-kernel-debuging-using-kdump-and-crash/.

I need to get the crash file from people having the freeze in order to fix it, so in the case you have some time :)

**Comment by ssokolow** [comment]
At the moment, I have far too much time tied up in catching up a slipped milestone in my degree project to promise anything.

However, do you know if kdump is supposed to dump nothing at all if you forget to install the ddebs?

I ask because, before I gave up on LIRC and uninstalled the driver for my StreamZap IR remote earlier this year, I did every step for installing kdump except installing the kernel debug information (that step was missing from the instructions I was following) and forcing a crash to test it (not sure why I didn't do that), and it's still set up that way... but no dump was generated. At the time, I just assumed it was freezing hard enough to block kdump but it didn't dump anything here either.

**Comment by zedtux** [comment]
Well, the debug symbols are useful in the case you would like to debug your self, as far as I know. So in the case you only want to help me, and generate the crash file, you shouldn't need the debug symbols.

**Comment by ssokolow** [comment]
Yes, but the question is whether it's the lack of debug symbols, the kernel crash itself, or something else that resulted in no new file being written to `/var/crash` when Douane froze my system.

**Comment by zedtux** [comment]
>Yes, but the question is whether it's the lack of debug symbols, the kernel crash itself, or something else that resulted in no new file being written to /var/crash when Douane froze my system.

The debug symbols are used only to show, in the stack trace that you got from the crash file, the name of the methods. So with or without them, as far as I know, the crash file will be generated the same way.

> Wait... create a dump in the swap partition... [...]

What do you mean with "in the swap partition" ? The crash files are stored in `/var/crash/`. You have to care about the size of the partition where the `/var/` folder is.

**Comment by ssokolow** [comment]
> During the next minute(s), your compute will create a dump in the swap partition, then reboot and move the dump to the /var/crash folder, and finaly boot to your environment.

From your blog post.

As for the `/var/` folder, it's on a drive with 27GiB free.

**Comment by zedtux** [comment]
Mmm .... then I'm not really sure .. now even if you have 16GiB of RAM, you're surely not have that amount of data to dump.

Just give it a try :)

**Comment by ssokolow** [comment]
I already had kdump set up according to your instructions (except for the debugging symbols) before Douane froze my kernel but no dump was produced.

That's why I'm asking if you know whether a lack of symbols will prevent the dump from being written.

**Comment by zedtux** [comment]
Has your system booted a second kernel and moved your session to it ?

**Comment by ssokolow** [comment]
For both the LIRC crasher and this one, it hard-froze with no clue what happened.

KMS-less nVidia binary drivers stuck displaying the last image they were displaying at the time of the freeze, sshd non-responsive to new connections, and no dump or relevant kernel log entries in `/var` after waiting a few minutes and then rebooting.

**Comment by zedtux** [comment]
Mmm have you answered 'yes' to the installation question about the reboot ?

> During the installation, you will be asked if you want to it to manage the reboot of the machine. In the case you answer yes to this question, it means that when you will request your computer to reboot, it will not do a full reboot (so avoid all the BIOS step) and boot a new kernel (hot reboot). If you desire to perform a full reboot, then you need to execute sudo coldreboot.
If you answer no to the question, you're going to keep the normal behavior.

**Comment by ssokolow** [comment]
I can't remember, but I probably chose 'no' because, when I reboot through a means other than "power outage", it's usually because I need to reset wedged firmware in some non-hotpluggable device like a bargain-basement DVD+R drive. (They tend to wear out after 500-600 discs burned, so I get the cheapest ones I can find.)

**Comment by zedtux** [comment]
Okay, it could be the reason why you don't have the crash file (I mean, I never tried anything else than what I wrote in my blog article).

Now answering 'yes' would reboot on a new kernel on hot restart, but you can use a cold restart in order to really restart your machine.

If I may suggest you, try using the 'yes' answer and see if it's better, then you can revert to the 'no' answer. Just to clarify that point.

**Comment by ssokolow** [comment]
The problem is that I don't have time to intentionally reboot any time soon and, if I leave it on by default, I'd:

1. forget
2. do a warm reboot
3. only realize what I'd done after spending several minutes waiting for my complex, heavy desktop loadout to boot (with human intervention required because Pidgin has no "ignore self-signed IRC SSL cert" option by design, times out SSL handshaking very quickly, and receives updates frequently enough that I don't feel like maintaining a patched fork).
4. curse up a storm
5. turn off warm rebooting and reboot again
6. be grumpy

**Comment by zedtux** [comment]
Alright, sure. In the case you have time later, I will be more than happy to get a crash file or a PR ;) Anyway, thanks !

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/53).
