### ISSUE TITLE
Installation problems - Unable to use 'systemctl' command to follow with instructions

### ISSUE THREAD

**Issue by Greenheart** [Douane/Douane#54]
Sorry if this is obvious, but I'm new to Linux and would be really thankful for some guidance.

I'm running Ubuntu 14.04, which doesn't include `systemd` and the `systemctl`-command.
According to [this answer](https://askubuntu.com/questions/304860/what-is-the-systemctl-equivalent/496385#496385), it's possible to get this working on my system, but I didn't get it to work.

Do I have to use systemctl to finish [this step](https://github.com/Douane/Douane/wiki/Compilation#the-daemon) or are there alternative tools?

Thanks in advance!

**Comment by zedtux** [comment]
As of now, nobody has implemented `systemd` in Douane, but I would be more than happy to get a PR.

**Comment by Greenheart** [comment]
Thanks for the quick reply! :smile: 

I might have expressed myself unclearly.

I have trouble *compiling and installing* Douane since my system can't use the `systemctl`-command.
When I try to [install the daemon](https://github.com/Douane/Douane/wiki/Compilation#the-daemon) and run this step

> Now you need to start it:
>
```systemctl daemon-reload```

i get `systemctl: command not found`

![command not found](https://cloud.githubusercontent.com/assets/6125097/11930072/96cc94ca-a7e0-11e5-9249-0b5c6e2fd61e.png)

How do I proceed with the installation?
