### ISSUE TITLE
No notification for SSH connections

### ISSUE THREAD

**Issue by rjzak** [Douane/Douane#55]
SSH connections die when:
1) SSH connection already established
2) Douane service started.

Douane seems to not be aware of SSH, and the connection dies from a timeout. This also affected a local VNC connection to a locally running VM.

**Comment by zedtux** [comment]
This sounds strange. Douane should block and notify you about it. The behavior you've described is similar to when Douane is blocking the app but you do not have the dialog process running, don't you?

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/55).
