### ISSUE TITLE
Docker compatibility

### ISSUE THREAD

**Issue by Sharsie** [Douane/Douane#56]
So I tried to run some docker containers, namely syncthing with Douane running on the host computer. The docker container has no issues connecting to the internet, which is fine, however, Douane Dialog keeps prompting me for applications trying to access the network from inside the container and then crashing once I press Allow/Deny
The issue is as follows:
Inside the docker container, there is an application at /usr/bin/syncthing
The host does not have access to this file (/usr/bin/syncthing on the host does not exist)
When I start the container, Douane Dialog prompts me for an action, clicking Allow or Deny crashes both dialog process and the daemon ( I assume this is because it cannot sha256sum the file?)
The last messages from the log are

```
[netlink_listener.cpp::NetLinkListener:90]: NetlinkListener::send_rule...
[netlink_listener.cpp::NetLinkListener:163]: NetlinkListener::build_message...
[netlink_listener.cpp::NetLinkListener:97]: NetlinkListener::send_rule ALLOW for /usr/bin/syncthing...
[rules_manager.cpp::RulesManager:89]: Currently 0 pending rules`
```

I was looking for a way to circumvent this and so far I found out the only way I can do this is to copy the application from the container to the host and add it to the rules

So I guess I'm writing this in case someone comes accross the same issue. It would probably be nice if there was a check before the daemon and dialog crashes if it cannot find the application

**Comment by Sharsie** [comment]
Well I have been getting kernel panics I am not sure if this is all from douaned, or whether this is because of the docker+douane combo (it does not seem to crash when no docker container is running, but it can be stable for a day and then crash), if anyone is interested i'm also posting backtrace for both panics I managed to crashdump (first one came from sshd - I have a tunnel to a VPS that is being refreshed periodically, second one is straight from douaned - in both douane is mentioned) - I do not have any experience debugging crashdumps, so if anyone can lend a hand, I'd appreaciate it.
[http://pastebin.com/4ZZvG7ZZ](sshd)
[http://pastebin.com/NMc1imzh](douaned)

**Comment by zedtux** [comment]
Hello and thank you @Sharsie for you issue.

I never tester Douane and Docker together and what you're explaining seems right. Douane has been built for a non virtualised environment. For sure it needs to be implemented but for now, I'm sorry it's not taken into account.

I should build a list of things "TODO" on the main page.

**Comment by zedtux** [comment]
@Sharsie can you please double check you links?

**Comment by Sharsie** [comment]
Hey there zedtux, sorry, it must have expired even though I chose "never expire"... anyway, i'll try again from a pastebin account:

sshd:
http://pastebin.com/QJTnghxH
douaned:
http://pastebin.com/TLJHihqD 
http://pastebin.com/BHAg91Us
http://pastebin.com/SSYqNkCH
http://pastebin.com/EV8TPNRQ

One more thing, the last log is from today, I turned off all docker containers to see what happens and it paniced anyway, so I suppose it might be another issue
I am not entirely sure what that backtrace says, but I can provide more debugging info if need be

**Comment by zedtux** [comment]
@Sharsie thank you for the repost of the files.

The issue is coming from one of the 2 lines [from here](https://github.com/Douane/douane-dkms/blob/master/douane.c#L881).

`ip_header->saddr` and `ip_header->daddr` doesn't have the expected content and my first guess would be that the IP addresses aren't in IPv4 format but IPv6 which I never tried.

In my eyes, the first thing is to add a `printk` showing those addresses when `DEBUG` is defined and then run it again and see what is inside.

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/56).
