### ISSUE TITLE
kernel module compile

### ISSUE THREAD

**Issue by thwaller** [Douane/Douane#57]
After installing dependencies, I get to here on the procedure:
git clone https://github.com/Douane/douane-dkms
cd douane-dkms
sudo make dkms

After the last line in the process, I get the following:
Makefile:77: recipe for target 'dkms' failed
make: *** [dkms] Error 1

I am running:
Release 16.04 LTS (Xenial Xerus) 64-bit
Kernel Linux 4.4.0-30-generic x86_64

**Comment by zedtux** [comment]
Hello @thwaller,

You should better read the documentation :)
First paragraph:

```
Dependencies

In order to compile Douane, it is necessary to install a number of libraries before building. Further information on dependencies is given at https://github.com/Douane/Douane/wiki/Dependencies
```

**Comment by thwaller** [comment]
@zedtux 
As I started it out, "after install dependencies". They are all installed. I have read the whole procedure.

**Comment by zedtux** [comment]
Sorry @thwaller, I went to fast through your issue. Can you please give a try to this: Douane/douane-dkms#15 ?

**Comment by thwaller** [comment]
Installing Douane Linux kernel module version 0.8.2...
mkdir: cannot create directory ‘/usr/src/douane-0.8.2’: File exists
Makefile:77: recipe for target 'dkms' failed
make: *** [dkms] Error 1

**Comment by thwaller** [comment]
All is good. Deleted that directory, now install is proceeding. Thanks.

**Comment by thwaller** [comment]
@zedtux - now from running here:
~/Douane/douane-dialog$ make
I get a bunch of errors. I am in "The Dialog Process".
Here is the beginning of it:

xxxxxx@xxxxxx:~/Douane/douane-dialog$ make
g++ -pedantic -Wall -W -g `pkg-config --cflags --libs liblog4cxx dbus-c++-1 gtkmm-3.0` -DDOUANE_VERSION=\"0.0.1\" -o dbus/dbus_client.o -c dbus/dbus_client.cpp
In file included from /usr/include/glibmm-2.4/glibmm.h:96:0,
                 from /usr/include/gtkmm-3.0/gtkmm.h:87,
                 from dbus/../gtk/gtk_process_icon.h:5,
                 from dbus/../network_activity.h:5,
                 from dbus/douane.h:8,
                 from dbus/dbus_client.h:7,
                 from dbus/dbus_client.cpp:1:
/usr/include/glibmm-2.4/glibmm/binding.h:327:41: error: macro "bind_property" requires 4 arguments, but only 3 given
     BindingFlags flags = BINDING_DEFAULT)
                                         ^
/usr/include/glibmm-2.4/glibmm/binding.h:510:41: error: macro "bind_property" passed 5 arguments, but takes just 4
     const T_functor_from& transform_from)

**Comment by thwaller** [comment]
I also do not have this "Now you should got a Douane application in your applications"

**Comment by zedtux** [comment]
@thwaller can you try this PR: Douane/douane-dialog#9 ?

**Comment by thwaller** [comment]
Ok, I have done that and it did complete but I saw a few warnings pop up in there. My issue now is that with all installed, there is nothing in applications to run a gui and it is crashing a lot (system crashes caused by Douane). It is no longer asking what to do when access is attempted and all is denied access. All I can do is stop the service.

If there is no fix, is there an uninstall to remove everything? I am most concerned about changes that may have impact system wide. Ex. I got a system lockup from Thunderbird when a new email notification popped up.

**Comment by zedtux** [comment]
Everything is installed in `/opt/douane` and in the systemd folder.

Now regarding a fix, there is this PR Douane/douane-dkms#16 where @Guimli tries to solve the kernel freeze issue.

**Comment by thwaller** [comment]
Ok. Well first, is there anything except the service that may cause issues? I can easily just stop that. I seem to get locks even with the service stopped though, so I believe there is more. Where is the service set to run automatically?

Second, I assume that the kernel freeze issue is not yet resolved? I looked over the link and it appears it is not yet a solution?

**Comment by thwaller** [comment]
@zedtux - what/where am I specifically looking for in regard to the systemd folder? I am able to follow all you have said thus far, but am unclear only on that part. Unless I am looking in the wrong place, nothing is as cleat as the "douane" directory in there.

**Comment by zedtux** [comment]
Regarding the kernel module, you can just go to the kernel module sources (folder douane-dims) and use `make cleandkms` which will uninstall and remove the kernel module from your kernel.

Regarding systemd, it's standard, you can search on this internet (sorry I don't know by heart).

**Comment by thwaller** [comment]
Thanks. I am still not following you with systemd. What is it in that folder I am to delete or remove? Regarding a search, I am not sure what I am searching for. I can locate the systemd folder, I just do not know what was placed in there. I hope that makes sense.

**Comment by zedtux** [comment]
Sorry for not having being clear enough. You should have to remove the file in [that folder](https://github.com/Douane/douane-daemon/tree/master/system.d).

**Comment by thwaller** [comment]
No problem at all. I was able to figure it out by review of the makefile's. The link you provided confirmed I did get it correct, so that is good. Sorry I had to remove at this time, hope to give it a go again soon. :)

**Comment by zedtux** [comment]
Sorry for the situation, unfortunately I don't have so much time for now to work on this project. Hopefully, next year I should have more time.
