### ISSUE TITLE
Error on compiling deamon

### ISSUE THREAD

**Issue by Kosti1** [Douane/Douane#58]
g++ -pedantic -Wall -W -g `pkg-config --cflags --libs liblog4cxx dbus-c++-1` -DDOUANE_VERSION=\"0.9.0\" -o dbus/dbus_server.o -c dbus/dbus_server.cpp
In file included from dbus/dbus_server.h:6:0,
                 from dbus/dbus_server.cpp:1:
dbus/douane.h:9:50: fatal error: interface/org_zedroot_douane_adaptor.h: No such file or directory
 #include "interface/org_zedroot_douane_adaptor.h"
                                                  ^

**Comment by zedtux** [comment]
Thank you @Kosti1 for your issue. Please open daemon issues on [the daemon repository](https://github.com/Douane/douane-daemon) as described in the project [architecture documentation](https://github.com/Douane/Douane/wiki/Architecture).

Then please follow the steps from [the compilation documentation](https://github.com/Douane/Douane/wiki/Compilation) and you shouldn't have this issue anymore.
