### ISSUE TITLE
sendmsg: Connection Refused

### ISSUE THREAD

**Issue by cmalkus** [Douane/Douane#59]
I get the following error in my log file when I turn the configurator on. I also have a red notification next to the switch that says `D-bus service org.zedroot.Douane not found` on mouseover 

`30/07/2016 16:02:18  INFO: Loaded 136 Freedesktop desktop files`
`30/07/2016 16:02:18  INFO: Loaded 0 rules`
`30/07/2016 16:02:18 ERROR: Error while calling sendmsg: Connection refused`
`30/07/2016 16:02:18 ERROR: Unable to send message`

I am running Ubuntu 16.04 and I installed via the instructions found here https://github.com/Douane/Douane/wiki/Compilation

I also had to manually create the rules file and add an empty object `{}`

**Comment by zedtux** [comment]
I have re-opened the issue at the right place.
