### ISSUE TITLE
Cannot Compile Daemon

### ISSUE THREAD

**Issue by Hugo14453** [Douane/Douane#60]
Hello!

I think I messed up my installation of boost...

I'm getting this error message while attempting to compile daemon:
http://pastebin.com/NzzBqNG6

Thanks for any help

**Comment by zedtux** [comment]
Hello @Hugo14453,

Can you please post the output of the following command:

```
$ lsb_release -a
```

**Comment by zedtux** [comment]
Since there's no update on this issue, I'm closing it.
