### ISSUE TITLE
Fix Arch PKGBUILD 

### ISSUE THREAD

**Issue by boussou** [Douane/Douane#64]
I tried to build it on Arch OpenRC. To make it work I had to change the **pkgver** which was returning empty.

as below (at the **printf** line):

```
	pkgver() {
	  cd "$srcdir/douane-daemon"
	  # Use the tag of the last commit
	  printf "%s.%s"  "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
	}

```

**Comment by boussou** [comment]
The same applies to 

1. douane-configurator
2. douane-dialog


I also have a suggestion: please remove the dbus dependancy so that I don't have to edit the build file.
douane build perfectly without it.

**Comment by zedtux** [comment]
Hello @boussou,

Sorry but I'm not taking care of the packaging, so I'm not gonna change it, but feel free to do it :)

> please remove the dbus dependancy

This I can't as it's a strong dependency of Douane (all the parts are talking to each other through DBus)

**Comment by boussou** [comment]
That will be for the record.
I build all components fine, but I am using manjaro-openrc 
https://sourceforge.net/projects/manjaro-openrc/ and I think it would need some effort to make it work.
