### ISSUE TITLE
Ubuntu 16.04 X64: D-Bus service org.zedroot.Douane not found

### ISSUE THREAD

**Issue by x-solid** [Douane/Douane#65]
Hello!

I'm trying to get Douane running on Ubuntu 16.04 x64.
There is a exclamation mark next the filter network traffic switch. Moving the mouse cursor on it, the error message is shown. -> screenshot. ![douane-configurator](https://cloud.githubusercontent.com/assets/25086210/21902955/34b92550-d8fe-11e6-8625-de6acbe1c463.png)

It is possible to switch it on. The configurator asks for root the password. Then the terminal shows the douane service has successfull been started, but no application is getting blocked.

**Comment by zedtux** [comment]
Hello @x-solid,

Thank you for giving a try to Douane.
Can you please `tail` the douane log as described in [the debugging documentation](https://github.com/Douane/Douane/wiki/Debugging) please?

**Comment by x-solid** [comment]
Hello zedtux

Sure, I think Douane is a great idea und I would really like to get it running on my machine.
Currently I installed it on a VM based on a new installation of Ubuntu 16.04 x64.

Here I have the douane dialog and daemon log for you:

[douane.log.txt](https://github.com/Douane/Douane/files/703525/douane.log.txt)

**Comment by zedtux** [comment]
So the error is the following:

```
Error while calling sendmsg: Connection refused
```

The daemon process is not able to connect to the kernel module (douane-dkms). Can you please export the logs from the `kern.log` relating to Douane please?

**Comment by x-solid** [comment]
It seems something went wrong in the line douane: module verification failed

```
Jan 13 15:16:36 test-virtual-machine kernel: [   21.896264] ISO 9660 Extensions: RRIP_1991A
Jan 13 15:20:17 test-virtual-machine kernel: [  243.994532] douane: module verification failed: signature and/or required key missing - tainting kernel
Jan 13 15:20:17 test-virtual-machine kernel: [  244.000901] douane:1190:initialize_module: Initializing module
Jan 13 15:20:17 test-virtual-machine kernel: [  244.000924] douane:1206:initialize_module: Kernel module is ready!
Jan 13 15:20:17 test-virtual-machine kernel: [  244.039587] douane:680:task_has_open_file: fd_null_max: 0 | MAX_FD_NULL: 9
Jan 13 15:20:17 test-virtual-machine kernel: [  244.039594] douane:794:print_tcp_packet: TCP | [seq:1060859533|ack_seq:3683734676]	FLAGS=-A---- | TGID 0:	192.168.43.18:51464 --> 91.189.88.149:80 (/usr/lib/apt/methods/http|swapper/0) {W:1924|0} NF_ACCEPT.
Jan 13 15:20:17 test-virtual-machine kernel: [  244.039595] douane:1110:netfiler_packet_hook: NF_ACCEPT (No daemon).
```

Unfortunately the kern.log is too big to attach. Grew up to 39 MB in 15 minutes

**Comment by zedtux** [comment]
So based on your comment and [this SO answer](http://stackoverflow.com/questions/24975377/kvm-module-verification-failed-signature-and-or-required-key-missing-taintin), it looks like you have a security option enabled in your kernel which prevents the Douane kernel module to run properly.

**Comment by x-solid** [comment]
Thank you. Well, it seems to me this Ubuntu kernel is compiled with the security option enabled by default. 
Can you please tell me which version of Ubuntu 16.04 you were successfully using in[ this kernel topic](https://github.com/Douane/douane-dkms/issues/3)?

**Comment by zedtux** [comment]
As mentioned in my last comment of pointed topic: Ubuntu 16.04.1.

So you say you haven't enabled any special features? It's the first time I see this issue.

**Comment by x-solid** [comment]
Yes, I didn't. Ubuntu 16.04.1 AMD64 installation is quite simple and I can't remember such an special option. May be it is because I installed it in a VM and there might be secure boot enabled in virtual bios (I wasn't able to check that up to now). As descriped here, there is a [depency](http://askubuntu.com/questions/773734/how-to-install-module-ko-module-without-kernel-signature-or-kernel-rebuild-in-ub/827534) to signed kernel modules.

Did you install the x86 oder the amd64 Ubuntu 16.04.1?

Today I installed douane on Ubuntu 14.04 32bit. No VM this time, no secure boot. 
It is working fine. Really enjoy it!

**Comment by zedtux** [comment]
The link you gave is really interesting, thank you.

Can you please open a ticket in the [daemon](https://github.com/Douane/douane-dkms) repository with this link?

> Did you install the x86 oder the amd64 Ubuntu 16.04.1?

I am always using the 64 bits version.

> Today I installed douane on Ubuntu 14.04 32bit. No VM this time, no secure boot.
> It is working fine. Really enjoy it!

That's cool man 😃 👍
