### ISSUE TITLE
Douane fails to compile

### ISSUE THREAD

**Issue by darknessenvelops** [Douane/Douane#66]
Douane failed to compile. The terminal log is attached. I tried everything I could think of. This was on a Mint 18 Mate 64-bit system. Please fix these compilation errors!
[Compilation impossible.txt](https://github.com/Douane/Douane/files/705562/Compilation.impossible.txt)

**Comment by zedtux** [comment]
```
dbus/../tools.h:13:25: fatal error: openssl/sha.h: No such file or directory
```

Looks like you're missing a dependency. The documentation has been made for Debian and Ubuntu, you should not have any issues, but if it's the case, I can update the documentation for Mint. Just let me know the package you have installed in order to fix the build issue and I'll change it.

**Comment by zedtux** [comment]
Since you're not updating the issue, I'm closing it.
