### ISSUE TITLE
Git communication blocked but not detected

### ISSUE THREAD

**Issue by ireallydontexist** [Douane/Douane#67]
Salut,

The firewall works pretty well to detect and allow/block most of my apps... except git (command line).
During a `git clone`, the traffic is blocked but the Douane dialog doesn't show up.

Any idea ?

Logs:
```
21/01/2017 22:01:01 | daemon | DEBUG | [rules_manager.cpp::RulesManager:27]: No rule found for /usr/lib/git-core/git-remote-http
21/01/2017 22:01:01 | daemon |  INFO | [rules_manager.cpp::RulesManager:57]: Currently 1 pending rules
21/01/2017 22:01:01 | daemon | DEBUG | [dbus/dbus_server.cpp::DBusServer:48]: DBusServer::signal_new_unknown_activity...
21/01/2017 22:01:01 | daemon | DEBUG | [dbus/douane.cpp::Douane:58]: Douane::emit_new_activity_to_be_validated_signal...
21/01/2017 22:01:01 | daemon | DEBUG | [dbus/douane.cpp::Douane:66]: Firing D-Bus signal NewActivityToBeValidated...

```

**Comment by ireallydontexist** [comment]
Pb found, in fact the douane-dialog did a segfault. So nobody was here to get the D-bus signal.

**Comment by zedtux** [comment]
Salut @ireallydontexist,

Any chance you post the sefault in this issue please?

**Comment by ireallydontexist** [comment]
Unfortunately, no chance.... the terminal history was not long enough...
