### ISSUE TITLE
douane-dialog crashing

### ISSUE THREAD

**Issue by AshotN** [Douane/Douane#69]
I just installed Douane and got a couple of prompts for SSH/Java/Telegram but now I'm trying to use Spotify and it won't give me an option to allow it.

**Comment by zedtux** [comment]
Can you please check the Douane log file in order to check what's going on?

**Comment by AshotN** [comment]
The log is really long and contains some information I'd rather not share on Github, I'm hoping this snippet is relevant if not I'll share the whole log via a more private medium

> 02/02/2017 23:17:34 | daemon | DEBUG | [rules_manager.cpp::RulesManager:27]: No rule found for /usr/share/spotify/spotify
02/02/2017 23:17:34 | daemon |  INFO | [rules_manager.cpp::RulesManager:57]: Currently 5 pending rules
02/02/2017 23:17:34 | daemon | DEBUG | [dbus/dbus_server.cpp::DBusServer:48]: DBusServer::signal_new_unknown_activity...
02/02/2017 23:17:34 | daemon | DEBUG | [dbus/douane.cpp::Douane:58]: Douane::emit_new_activity_to_be_validated_signal...
02/02/2017 23:17:34 | daemon | DEBUG | [dbus/douane.cpp::Douane:66]: Firing D-Bus signal NewActivityToBeValidated...
02/02/2017 23:17:34 | daemon | DEBUG | [rules_manager.cpp::RulesManager:27]: No rule found for /usr/share/spotify/spotify
02/02/2017 23:17:34 | daemon |  INFO | [rules_manager.cpp::RulesManager:57]: Currently 5 pending rules
02/02/2017 23:17:34 | daemon | DEBUG | [dbus/dbus_server.cpp::DBusServer:48]: DBusServer::signal_new_unknown_activity...
02/02/2017 23:17:34 | daemon | DEBUG | [dbus/douane.cpp::Douane:58]: Douane::emit_new_activity_to_be_validated_signal...

**Comment by zedtux** [comment]
> Currently 5 pending rules

I think the douane-dialog process has crashed so it cannot popup anymore. Restarting it should fix your issue.
Can you please check that?

**Comment by AshotN** [comment]
I restarted my computer and it didn't solve it, how can I restart the dialog process alone.

**Comment by zedtux** [comment]
Normally, after the compilation and installation steps, you started it using `/opt/douane/bin/douane-dialog &`.

You can first check you have no running douane-dialog process on your machine.
Then you can run it again using the same command.

**Comment by AshotN** [comment]
I killed the process and used the command to restart it, at first it froze so I killed it and started it again and it started popping up Spotify/Electron etc...

So the problem is now why the dialog is crashing rather than a Spotify specific issue

**Comment by zedtux** [comment]
> So the problem is now why the dialog is crashing rather than a Spotify specific issue

Agree

**Comment by zedtux** [comment]
@AshotN do you have some news regarding your issue?

**Comment by AshotN** [comment]
I haven't been running the Douane as it renders some applications useless :( 

I also haven't been on Linux these past few days, but if you have any suggestions on how I can debug it I'll give it a shot over the weekend

**Comment by zedtux** [comment]
@AshotN everything you need to know about debugging is on [this Wiki page](https://github.com/Douane/Douane/wiki/Debugging).

**Comment by tk421storm** [comment]
I'm having the same issue here, running Ubuntu 16.04 with xfce4. When i start up the computer, the douane service is running, but it can't seem to create dialogues. Force-quitting the douane-dialog process and re-starting it doesn't make a difference. All the new apps get added to a "pending" list:

21/07/2017 17:10:48 | daemon |  INFO | [rules_manager.cpp::RulesManager:57]: Currently 2 pending rules
21/07/2017 17:10:48 | daemon | DEBUG | [dbus/dbus_server.cpp::DBusServer:48]: DBusServer::signal_new_unknown_activity...
21/07/2017 17:10:48 | daemon | DEBUG | [rules_manager.cpp::RulesManager:27]: No rule found for /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
21/07/2017 17:10:48 | daemon | DEBUG | [dbus/douane.cpp::Douane:58]: Douane::emit_new_activity_to_be_validated_signal...
21/07/2017 17:10:48 | daemon |  INFO | [rules_manager.cpp::RulesManager:57]: Currently 2 pending rules
21/07/2017 17:10:48 | daemon | DEBUG | [dbus/dbus_server.cpp::DBusServer:48]: DBusServer::signal_new_unknown_activity...
21/07/2017 17:10:48 | daemon | DEBUG | [dbus/douane.cpp::Douane:58]: Douane::emit_new_activity_to_be_validated_signal...
21/07/2017 17:10:48 | daemon | DEBUG | [dbus/douane.cpp::Douane:66]: Firing D-Bus signal NewActivityToBeValidated...
21/07/2017 17:10:48 | daemon | DEBUG | [dbus/douane.cpp::Douane:66]: Firing D-Bus signal NewActivityToBeValidated...

**Comment by zedtux** [comment]
@tk421storm please run the dialog process in debug mode and check the logs

**Comment by mrmotallebi** [comment]
I've noticed that the dialog process has issues with AppImage programs. For example, it dies whenever I try to grant access to [NextCloud client](https://github.com/nextcloud/client). I don't know if it's because the files AppImage creates in `/tmp` with root:root owner or something else.

**Comment by zedtux** [comment]
Thank you @mrmotallebi for your update on this issue.

Someone caught that the dialog process is suffering of concurrency issue. Maybe this "AppImage" is doing parallel stuff crashing the dialog 😞

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/69).
