### ISSUE TITLE
Monitor filesystem access

### ISSUE THREAD

**Issue by rchipka** [Douane/Douane#71]
It would be nice if Douane would implement filesystem access controls.

The macOS app [Hands Off!](https://www.oneperiodic.com/products/handsoff/) does this in a way similar to Little Snitch.

Are there any plans to implement this feature? If not, would a pull request implementing this feature be accepted?

**Comment by zedtux** [comment]
This feature wasn't foreseen but it looks interesting. Nevertheless it sounds like breaking the UNIX principle to me:

> Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".

2 options in my eyes:

- Build a plugin architecture
- Build another app based on Douane

> Are there any plans to implement this feature?

No, it wasn't plan.

> If not, would a pull request implementing this feature be accepted?

Of course, and I'll be more than happy to do it.

**Comment by intika** [comment]
Humm you are looking for a kind a HIPS ^^ thats cool indeed, but i think this is out of the scope of douane... 
There is a lot of other solutions that could be combined to douane to do the job

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/71).
