### ISSUE TITLE
Incoming connections

### ISSUE THREAD

**Issue by Forkest** [Douane/Douane#73]
Feature request of all the existing functionality, but for incoming connections and port opening.

**Comment by zedtux** [comment]
@Forkest I don't think it is technically possible as Douane is an application traffic firewall, which means Douane needs to know the application generating (or in this case receiving) the traffic.

**Comment by Forkest** [comment]
Knowing which application tries to receive the traffic and be able to block it is the whole point of this request. I don't know how exactly it could be implemented, but it should be possible, since [you can easily list](https://www.cyberciti.biz/tips/linux-display-open-ports-owner.html) opened ports and the corresponding apps.

**Comment by amarildojr** [comment]
You could use my set of incoming filter rules to at least block everything that might be risky, and use Douane to filter outcoming calls. I'll test this tonight to see if it's possible.

My rules: https://github.com/amarildojr/Firewall/blob/master/Output

**Comment by zedtux** [comment]
@Forkest you're probably right, it should be possible.

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/73).
