### ISSUE TITLE
Masses of BLOCKED PUSH logs printed to the user

### ISSUE THREAD

**Issue by NotANormie** [Douane/Douane#74]
I am not sure whether this is my own fault from compiling it incorrectly or what not... Yet, I whenever I drop down to TTY when I need to make some core changes in the system (I am on Debian Sid), I am spammed periodically with "douane:430:push: BLOCKED PUSH: process_path is blank." 

This has been occurring for a while but I have ignored it and turned off logging as it causes thousands of megabytes of just that line to be repeated in the file.

Searching for this issue turns up this result which is a similar problem to what I am experiencing : https://thinkpad-forum.de/threads/207725-Absturzanalyse-Linux-Mint

**Comment by mauron85** [comment]
I guess this is related douane kernel module.

https://github.com/Douane/douane-dkms/blob/61023b91fbafab8e63d8c271ec25aa0929f2f643/douane.c#L428

And happens when process path is empty, which is apparently quite often for some processes.

**Comment by zedtux** [comment]
Thank you guys for having opened this issue.

Honestly I don't remember having so much output of this log ... it's wired. @mauron85 you pointed the right line of code.

Maybe activating the debug mode for the kernel module could help to understand what is going wrong. Could you please, both, try enabling the debug mode using [this page of the wiki](https://github.com/Douane/Douane/wiki/Debugging), and post here some lines around this line of log?

**Comment by NotANormie** [comment]
Alright, now I am being spammed in the kern.log with 
[17066.261510] douane:794:print_tcp_packet: TCP | [seq:2512035138|ack_seq:3170714102
[17066.261511] douane:1110:netfiler_packet_hook: NF_ACCEPT (No daemon).
[17066.261532] douane:680:task_has_open_file: fd_null_max: 0 | MAX_FD_NULL: 9
these three over and over again.
Also: douane:1095:netfiler_packet_hook: !!OOPS!! process_owner_path is blank but was filterable! !!OOPS!!
I have disabled it because if I left it on I would have 0 Bytes left.
I am going to guess that it has something to do with the daemon? 
All I really want is to disable messages completely at this point.

**Comment by NotANormie** [comment]
Alright, this is quite possibly the laziest solution ever (check attachments). Yet, seeing this remedied would be nice but isn't there a switch you can use in the config of douane-dkms where you can toggle off all messages and errors? 
![image](https://user-images.githubusercontent.com/29356754/27510694-7ab9edb0-590e-11e7-99b0-9c260e2af91b.png)

**Comment by zedtux** [comment]
@NotANormie I'm sorry you're spammed, but actually those messages indicates that Douane is not working correctly in your configuration.

Disabling this piece of code could lead you to kernel panics or daemon crashes. Be careful when changing the code :)

What is the output of `lsb_release -a`?

**Comment by NotANormie** [comment]
No LSB modules are available
I guess I forgot to compile something somewhere?
Disabling that specific message is not going to affect anything on my part since I have been using Douane for a long time with that message.

**Comment by zedtux** [comment]
Sorry, I forgot you mentioned you're on Debian sid :)

Okay, then if you don't have any crashes, I'm fine with that :)

Now that you're the only one having this issue, I suggest to close it but feel free to update it if needed ;)
