### ISSUE TITLE
Failed to start douane.service

### ISSUE THREAD

**Issue by pipiscrew** [Douane/Douane#76]
hi all,

Im sitting on : 
ArchLinux v4.13.11-1-ARCHx86

--

Compile all from : 
https://github.com/Douane/Douane/wiki/Archlinux-Packaging

with the exception on all PKGBUILD, I had to remove the `pkgver() { .. }` coz causes error.

trying to install **dkms-1-1-x86_64.pkg.tar** end up with : 
> ==> No kernel 4.13.12-1-ARCH headers. You must install them to use DKMS!

[edit]
installing **lts kernel** the packages can be installed without problem!

I can see the douane-configuration form, but a purple exclamation appear near 'fiter my network traffic' switch, on mouseover writes 'D-Bus service org.zedroot.Douane not found.'

running `systemctl start douane` or `systemctl start douane.service` or `systemctl start douane-reload` getting  

> Failed to start douane.service: Unit douane.service not found

running `systemctl start douane-daemon` outputs nothing 

[edit]
ok, the https://github.com/Douane/Douane/wiki/Archlinux-Packaging is outadated. 

found : 
https://aur.archlinux.org/cgit/aur.git/?h=douane-dialog-git
https://aur.archlinux.org/cgit/aur.git/?h=douane-daemon-git
https://aur.archlinux.org/cgit/aur.git/?h=douane-dkms-git
https://aur.archlinux.org/cgit/aur.git/?h=douane-configurator-git

compiling... I will update.

[edit]
*1*
git clone https://aur.archlinux.org/douane-configurator-git.git/
git clone https://aur.archlinux.org/douane-dkms-git.git/
git clone https://aur.archlinux.org/douane-daemon-git.git/
git clone https://aur.archlinux.org/douane-dialog-git.git/

*2*
makepkg -s for all^ 

the log4cxx lib is missing use yaourt to download it and compile it!

*3*
sudo pacman -U douane-dkms-git-0.8.2.r16.g6141fbb-1-x86_64.pkg.tar
sudo pacman -U douane-daemon-git-1-4-x86_64.pkg.tar
sudo pacman -U douane-dialog-git-1-3-x86_64.pkg.tar
sudo pacman -U douane-configurator-git-1-3-x86_64.pkg.tar

please see the attached images (@ 3rd click+zoom)...
![compiling1](https://user-images.githubusercontent.com/3852762/32797284-93102748-c971-11e7-93f2-8f73ccc584a9.jpg)
![compiling2](https://user-images.githubusercontent.com/3852762/32797285-933250ac-c971-11e7-83a1-1662114b8584.jpg)
![service failed](https://user-images.githubusercontent.com/3852762/32797291-9721d6d8-c971-11e7-8e5a-ce82816f14a5.jpg)

ref:
https://wiki.archlinux.org/index.php/Autostarting#Daemons

You can start your scripts or applications as daemons, see Daemon.

> systemd is the default init framework, replacing initscripts. The services which are started by systemd can be found in the subfolders of /etc/systemd/system/

went there no douane* file/folder

[edit]
search for init.d on all source files : 
![initd_hardcoded](https://user-images.githubusercontent.com/3852762/32798824-2a00e7f6-c976-11e7-9cf5-4f473a121839.png)

please advise!

**Comment by zedtux** [comment]
Thank you @pipiscrew for your issue.

Sorry for the late reply, I missed the notification about your issue. 😞

I developed Douane on a Debian distro, which wasn't using systemd at that time. You can see how Douane is installed in [this Makefile](https://github.com/Douane/douane-daemon/blob/master/Makefile#L44).

I guess a PR should be opened installing the missing systemd files.

**Comment by intika** [comment]
can you try with the last release, 
also you will need initscripts package 
https://pkgs.org/download/initscripts

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/76).
