### ISSUE TITLE
configurator shows wrong state

### ISSUE THREAD

**Issue by saitam1** [Douane/Douane#82]
When turning off both features in configurator it still doesn't let connect an app anywhere, which is not listed in rules. See screenshot:

![tele](https://user-images.githubusercontent.com/23245678/36268874-f613a802-1277-11e8-849a-f2bcd5a5c179.png)

Is there a solution?

**Comment by zedtux** [comment]
Thank you @saitam1 for this issue.

I'm a bit confused when I'm reading the issue's title and description. Just to be sure I got your point:

1. You started douane
2. You have allowed/denied access to the internet for an app
3. You switch off both features in the configurator
4. The allowed/denied app is allowed but all other apps are blocked?

Is that correct?

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/82).
