### ISSUE TITLE
Configurator GUI bug (switch buttons)

### ISSUE THREAD

**Issue by saitam1** [Douane/Douane#83]
Whenever you switch one of both button `ON` or `OFF` you have to type in the `sudo` password to have the changes taken in effect. If you just click `cancel` on the authentication form, the button will switch anyway to either `ON` or `OFF` (depending on the previous state). Even if it has no effect in the background, the GUI show a state which is not active.

**Comment by zedtux** [comment]
Thank you @saitam1 for your issue. I fully agree with your comment, please open it at [the right place](https://github.com/Douane/douane-configurator/issues).
