### ISSUE TITLE
Detailed question window ?

### ISSUE THREAD

**Issue by intika** [Douane/Douane#89]
How to display details on the question window  (ip and protocol) as the capture on https://github.com/Douane/Douane ?

**Comment by zedtux** [comment]
Those information was on the modal at the very beginning, and someone opened an issue asking to simplify it.
I wasn't really against it as the non-technical people aren't really looking at that information.
The idea was to have a kind of "More details" button or something which will give technical information.

The deamon process is aware of the IP addresses (source and destination) and also about ports. You can see it from [the network_activity.h file](https://github.com/Douane/douane-daemon/blob/master/network_activity.h)

**Comment by intika** [comment]
i can not find any commit about it on douane-dialog i guess it was made outside github
its in douane-dialog right ?

**Comment by intika** [comment]
okay i got it 
https://github.com/Douane/douane-dialog/commit/95c5f0c6d4393aac56ffa63fb18ac9cb173bc0b0#diff-40b74e5edde5efd915cfad9b676a6830

**Comment by intika** [comment]
will reverse that in my personal release here https://github.com/intika/douane-dialog-detailed 
for those how will be interested

**Comment by zedtux** [comment]
@intika why not implementing an option instead of doing your own fork?

**Comment by intika** [comment]
because just reverting that change is an easy thing to get done, but yeah you are right adding it as an option would contribute to the project instead of sparing it... 
To be honest here is the situation... i am looking for a firewall for application, your by design (kernel module) is the best one available right now, even better than opensnitch who can not watch every thing... but the problem is : a lot of work need to be done in your app to make it really efficient 
- Kernel module need to handle more connections (null path app/master app launching library/etc.) 
- Handeling app doing unusual connections 
- The configurator need to have a feature to edit rules 
- A tray app would be nice to have a central place to manage all this and also to watch the daemon 
etc. etc. 
its an amazing app but sill need some work for stabilisation and usability... 
Personally i would live fixing adding all those thing but i have just a few time to put on that, my main work takes a big part of my schedule

**Comment by zedtux** [comment]
I follow you 100%!

> i don't really know where to go from there

In my eyes, first thing first, open issues for all your points. Something like "The configurator need to have a feature to edit rules" is really easy and quick to do. But this needs should be well described (I guess you don't mean just editing. We should have an add, edit and delete action, right?).

When those issues are open, it could be that someone passing by will implement it. Otherwise, the day I can work again on Douane, I could consider working on it.

Also it would better explain your need. "Handeling app doing unusual connections" is unclear to me.
