### ISSUE TITLE
ubuntu 18.04 :c crash sometimes after Enable service trafic

### ISSUE THREAD

**Issue by mnavahan** [Douane/Douane#94]
Hi 
I install the same wiki .
After install any time i active "use douane to filter my network" 
my notebook randomly complimentary freeze

ubuntu 18.04 Freez  sometimes after Enable service trafic

**Comment by zedtux** [comment]
I guess your issue duplicates Douane/douane-dkms#3. Please contribute to the mentioned issue. All information are welcome in order to stabilise the app.
